name: Publish Sphinx docs to GitHub Pages

on:
  push:
    branches:
      - "main"
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f Library-Management-System/docs/requirements.txt ]; then
            pip install -r Library-Management-System/docs/requirements.txt
          else
            pip install sphinx
          fi

      - name: Build Sphinx HTML
        working-directory: Library-Management-System/docs
        run: |
          if [ -f Makefile ]; then
            make html
          else
            sphinx-build -b html source build/html
          fi

      - name: Debug: list build output
        run: |
          echo "=== ls -R Library-Management-System/docs/build/html ==="
          ls -R Library-Management-System/docs/build/html || true

      - name: Upload pages artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: Library-Management-System/docs/build/html

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v1

