name: Publish Sphinx docs to GitHub Pages

# 触发器：push 到 main 或手动触发
on:
  push:
    branches: ["master"]
  workflow_dispatch:

# 必要权限（官方建议）
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install dependencies
        # 优先使用你放在 Library-Management-System/docs/requirements.txt 的依赖
        run: |
          python -m pip install --upgrade pip
          if [ -f Library-Management-System/docs/requirements.txt ]; then
            pip install -r Library-Management-System/docs/requirements.txt
          else
            pip install sphinx
            # 如你使用特定 theme（例如 sphinx-book-theme / sphinx_rtd_theme），可在 requirements.txt 中指定
          fi

      - name: Build Sphinx HTML (use Makefile if exists, else sphinx-build)
        working-directory: Library-Management-System/docs
        run: |
          if [ -f Makefile ]; then
            make html
          else
            sphinx-build -b html source build/html
          fi

      - name: Debug: list build output
        run: |
          echo "=== ls -R Library-Management-System/docs/build/html ==="
          ls -R Library-Management-System/docs/build/html || true

      - name: Upload pages artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: Library-Management-System/docs/build/html

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4

